### ISSUE TITLE
Is ImplicitStreamSubscription supported?

### ISSUE THREAD

**Issue by Neftedollar** [OrleansContrib/Orleankka#158]
Is Orleankka works with ImpicitSubscribtion attribute?

This code 
```fsharp
type [<ImplicitStreamSubscription(IGolfScrapper.GolfScrapperResult.ChanelName)>]
  PgaDriveDistanceEstimator(log: ILogger<PgaDriveDistanceEstimator>, httpClient: HttpClient) =
      inherit TypedActor<unit>()
      override this.ReceiveT (msg) = task {
          match msg with
          | Activate a ->
              let stream = ActorSystem.streamOf(this.System,"sms", IGolfScrapper.GolfScrapperResult.ChanelName)
              let! subscribtion = stream.Subscribe(fun (IGolfScrapper.GolfScrapperResult.Scrapped d) -> ignore <| task {
                  let url = sprintf "MY SECRET URL" DateTime.UtcNow.Year
                  let! result = httpClient.GetAsync(url)
                  let! stream = result.Content.ReadAsStreamAsync()
                  let! json = Helpers.readGzipFromStream stream
                  let logMsg = sprintf """Got JSON %s """ json
                  log.LogInformation logMsg
                  printfn "%A" logMsg })
              return none()
          | _ -> return unhandled()
      }
      
      interface IPgaDriveDistanceEstimator.IPgaDriveDistanceEstimator
```

rise errors on the activation

```bash
fail: Orleans.Runtime.Dispatcher[101540]
      Error creating activation for Server.Grains.PgaDriveDistanceEstimator.PgaDriveDistanceEstimator. Message NewPlacement Request S127.0.0.1:11111:299086155*grn/9A23FCA8/00000000+golfScrapper@3477df87->S127.0.0.1:11111:299086155*grn/995E50AA/0000
0000@f4966c9c #249:
System.ArgumentNullException: Value cannot be null.
Parameter name: id
   at Orleankka.Utility.Requires.NotNull[T](T argument, String argumentName) in C:\Work\OSS\Orleankka\Source\Orleankka\Utility\Requires.cs:line 15
   at Orleankka.ActorPath.For(Type interface, String id) in C:\Work\OSS\Orleankka\Source\Orleankka\ActorPath.cs:line 25
   at Orleankka.ActorGrain.Initialize(IServiceProvider services, String id) in C:\Work\OSS\Orleankka\Source\Orleankka.Runtime\ActorGrain.cs:line 59
   at Orleankka.ActorGrainActivator.Create(IGrainActivationContext context) in C:\Work\OSS\Orleankka\Source\Orleankka.Runtime\ActorActivator.cs:line 17
   at Orleans.Runtime.GrainCreator.CreateGrainInstance(IGrainActivationContext context) in D:\build\agent\_work\7\s\src\Orleans.Runtime\Catalog\GrainCreator.cs:line 34
   at Orleans.Runtime.Catalog.CreateGrainInstance(String grainTypeName, ActivationData data, String genericArguments) in D:\build\agent\_work\7\s\src\Orleans.Runtime\Catalog\Catalog.cs:line 716
   at Orleans.Runtime.Catalog.SetupActivationInstance(ActivationData result, String grainType, String genericArguments) in D:\build\agent\_work\7\s\src\Orleans.Runtime\Catalog\Catalog.cs:line 519
   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Dictionary`2 requestContextData, Task& activatedPromise) in D:\build\agent\_work\7\s\src\Orleans.Runtime
\Catalog\Catalog.cs:line 507
   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message) in D:\build\agent\_work\7\s\src\Orleans.Runtime\Core\Dispatcher.cs:line 95
warn: Orleans.Runtime.Scheduler.WorkItemGroup[101215]
      Task [Id=2, Status=RanToCompletion] in WorkGroup [Activation: S127.0.0.1:11111:299086155*grn/9A23FCA8/00000000+golfScrapper@3477df87 #GrainType=Server.Grains.GolfScrapper+GolfScrapper Placement=RandomPlacement State=Valid] took elapsed time 0
:00:00.4951394 for execution, which is longer than 00:00:00.2000000. Running on thread System.Threading.Thread
fail: Orleans.Runtime.ReminderService.LocalReminderService[102915]
      Could not deliver reminder tick for [Players, GrainReference:*grn/9A23FCA8/0000000000000000000000000000000006ffffff9a23fca8+golfScrapper-0xB5537A83, 00:01:00, 2019-06-24 15:30:00.011 GMT, 2aac5ffc-86f2-439c-992c-1195642ce559, 31, Ticking], ne
xt 6/24/2019 3:31:12 PM.
Orleans.Runtime.OrleansException: Error creating activation for Server.Grains.PgaDriveDistanceEstimator.PgaDriveDistanceEstimator. Message NewPlacement Request S127.0.0.1:11111:299086155*grn/9A23FCA8/00000000+golfScrapper@3477df87->S127.0.0.1:11111
:299086155*grn/995E50AA/00000000@f4966c9c #249:  ---> System.ArgumentNullException: Value cannot be null.
Parameter name: id
   at Orleankka.Utility.Requires.NotNull[T](T argument, String argumentName) in C:\Work\OSS\Orleankka\Source\Orleankka\Utility\Requires.cs:line 15
   at Orleankka.ActorPath.For(Type interface, String id) in C:\Work\OSS\Orleankka\Source\Orleankka\ActorPath.cs:line 25
   at Orleankka.ActorGrain.Initialize(IServiceProvider services, String id) in C:\Work\OSS\Orleankka\Source\Orleankka.Runtime\ActorGrain.cs:line 59
   at Orleankka.ActorGrainActivator.Create(IGrainActivationContext context) in C:\Work\OSS\Orleankka\Source\Orleankka.Runtime\ActorActivator.cs:line 17
   at Orleans.Runtime.GrainCreator.CreateGrainInstance(IGrainActivationContext context) in D:\build\agent\_work\7\s\src\Orleans.Runtime\Catalog\GrainCreator.cs:line 34
   at Orleans.Runtime.Catalog.CreateGrainInstance(String grainTypeName, ActivationData data, String genericArguments) in D:\build\agent\_work\7\s\src\Orleans.Runtime\Catalog\Catalog.cs:line 716
   at Orleans.Runtime.Catalog.SetupActivationInstance(ActivationData result, String grainType, String genericArguments) in D:\build\agent\_work\7\s\src\Orleans.Runtime\Catalog\Catalog.cs:line 519
   at Orleans.Runtime.Catalog.GetOrCreateActivation(ActivationAddress address, Boolean newPlacement, String grainType, String genericArguments, Dictionary`2 requestContextData, Task& activatedPromise) in D:\build\agent\_work\7\s\src\Orleans.Runtime
\Catalog\Catalog.cs:line 507
   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message) in D:\build\agent\_work\7\s\src\Orleans.Runtime\Core\Dispatcher.cs:line 95
   --- End of inner exception stack trace ---
   at Orleans.Runtime.Dispatcher.ReceiveMessage(Message message) in D:\build\agent\_work\7\s\src\Orleans.Runtime\Core\Dispatcher.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask) in D:\build\agent\_work\7\s\src\Orleans.Core\Async\TaskExtensions.cs:line 101
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducerExtension.StreamConsumerExtensionCollection.DeliverToRemote(IStreamConsumerExtension remoteConsumer, StreamId streamId, GuidId subscriptionId, Object item, Boolean optim
izeForImmutableData, Boolean fireAndForgetDelivery) in D:\build\agent\_work\7\s\src\Orleans.Core\Streams\SimpleMessageStream\SimpleMessageStreamProducerExtension.cs:line 223
   at Orleans.Providers.Streams.SimpleMessageStream.SimpleMessageStreamProducer`1.OnNextAsync(T item, StreamSequenceToken token) in D:\build\agent\_work\7\s\src\Orleans.Core\Streams\SimpleMessageStream\SimpleMessageStreamProducer.cs:line 112
   at Server.Grains.GolfScrapper.ReceiveT@69-14.Invoke(Unit unitVar0) in C:\Users\roman.melnikov\source\repos\grootScheduler\GrootScheduler\GrootScheduler\Server\Grains\GolfScrapper.fs:line 69
   at FSharp.Control.Tasks.TaskBuilder.StepStateMachine`1.nextAwaitable() in C:\Users\humbo\source\repos\TaskBuilder.fs\TaskBuilder.fs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at Orleans.OrleansCodeGenRemindableMethodInvoker.Invoke(IAddressable grain, InvokeMethodRequest request) in D:\build\agent\_work\7\s\src\Orleans.Core\obj\Release\netstandard2.0\Orleans.Core.orleans.g.cs:line 977
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in D:\build\agent\_work\7\s\src\Orleans.Runtime\Core\GrainMethodInvoker.cs:line 91
   at OrleansDashboard.Metrics.GrainProfilerFilter.Invoke(IIncomingGrainCallContext context)
   at Orleans.Runtime.GrainMethodInvoker.Invoke() in D:\build\agent\_work\7\s\src\Orleans.Runtime\Core\GrainMethodInvoker.cs:line 72
   at Orleans.Runtime.InsideRuntimeClient.Invoke(IAddressable target, IInvokable invokable, Message message) in D:\build\agent\_work\7\s\src\Orleans.Runtime\Core\InsideRuntimeClient.cs:line 351
   at Orleans.Runtime.ReminderService.LocalReminderService.LocalReminderData.OnTimerTick(AverageTimeSpanStatistic tardinessStat, ILogger Logger) in D:\build\agent\_work\7\s\src\Orleans.Runtime\ReminderService\LocalReminderService.cs:line 583
```

**Comment by yevhen** [comment]
Hmm, looking at stacktrace I can see that Orleans is passing null id. Can you check that `IGolfScrapper.GolfScrapperResult.ChanelName` is not null?

**Comment by Neftedollar** [comment]
it's literal
```fsharp
type GolfScrapperResult =
    | Scrapped of DateTime
  module GolfScrapperResult =
    [<Literal>]
    let ChanelName = "GolfScrapperResult"
    let GlobalId = Guid.Empty
```

**Comment by yevhen** [comment]
@Neftedollar Still actual?

**Comment by Neftedollar** [comment]
I've moved to classic Orleans.

**Comment by yevhen** [comment]
ok
