### ISSUE TITLE
.Net Core 3 Preview 6 Idiomatic Example

### ISSUE THREAD

**Issue by andyhoyle** [OrleansContrib/Orleankka#159]
Repro steps (Windows):

```
git clone git@github.com:OrleansContrib/Orleankka.git
cd Orleankka
nake.bat
```
Result:
```
...
Pages\Logs.razor(20,16): error CS0169: The field 'Logs.logPanel' is never used [C:\Work\test\Orleankka\Samples\CSharp\FSM\ProcessManager\ProcessManager.csproj]
Pages\Jobs.razor(57,12): error CS0649: Field 'Jobs.jobId' is never assigned to, and will always have its default value null [C:\Work\test\Orleankka\Samples\CSharp\FSM\ProcessManager\ProcessManager.csproj]
...
```

Above errors not relevant to Idiomatic project

```
dotnet run --project Samples\CSharp\EventSourcing\Idiomatic\Idiomatic.csproj
```

Result:
```
Running example. Booting cluster might take some time ...


Unhandled Exception: System.Runtime.Serialization.SerializationException: Type 'System.Text.RegularExpressions.RegexReplacement' in Assembly 'System.Text.RegularExpressions, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' is not marked as serializable.
   at Orleans.OrleansTaskExtentions.<ToTypedTask>g__ConvertAsync|4_0[T](Task`1 asyncTask)
   at Orleans.OutsideRuntimeClient.StreamingInitialize()
   at Orleans.OutsideRuntimeClient.<StartInternal>g__ExecuteWithRetries|56_3(Func`1 task, Func`2 shouldRetry)
   at Orleans.OutsideRuntimeClient.StartInternal(Func`2 retryFilter)
   at Orleans.OutsideRuntimeClient.Start(Func`2 retryFilter)
   at Orleans.ClusterClient.Connect(Func`2 retryFilter)
   at Orleankka.DemoExtensions.Connect(ISiloHost host, Action`1 configure) in C:\Work\test\Orleankka\Samples\CSharp\Shared.cs:line 77
   at Example.Program.Main() in C:\Work\test\Orleankka\Samples\CSharp\EventSourcing\Idiomatic\Program.cs:line 28
   at Example.Program.<Main>()
```

Info:
```
dotnet --version
```
Result:
```
3.0.100-preview6-012264
```

**Comment by andyhoyle** [comment]
Tracked it down to an issue with the RegexStreamNamespacePredicate in Orleans codebase

**Comment by ReubenBond** [comment]
Perhaps we need custom serialization for that predicate (eg, to serialize the regex as a string), assuming it needs serialization at all. Could you open an issue against Orleans xref'ing this?

**Comment by andyhoyle** [comment]
Sure, will do. I copied the predicate to Orleankka to test it. This version works fine:
```

**Comment by yevhen** [comment]
Looks like this was fixed is StartsWithPredicate. Closing
